# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BGMUIExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BGMUIExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBGMUIExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BGMUIExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BGMUIExcel
    def Uiprefab(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def Bgmid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def Bgmid2nd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def Bgmid3rd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def BGMUIExcelStart(builder):
    builder.StartObject(5)

def Start(builder):
    BGMUIExcelStart(builder)

def BGMUIExcelAddUiprefab(builder, uiprefab):
    builder.PrependUint32Slot(0, uiprefab, 0)

def AddUiprefab(builder, uiprefab):
    BGMUIExcelAddUiprefab(builder, uiprefab)

def BGMUIExcelAddBgmid(builder, bgmid):
    builder.PrependInt64Slot(1, bgmid, 0)

def AddBgmid(builder, bgmid):
    BGMUIExcelAddBgmid(builder, bgmid)

def BGMUIExcelAddBgmid2nd(builder, bgmid2nd):
    builder.PrependInt64Slot(2, bgmid2nd, 0)

def AddBgmid2nd(builder, bgmid2nd):
    BGMUIExcelAddBgmid2nd(builder, bgmid2nd)

def BGMUIExcelAddBgmid3rd(builder, bgmid3rd):
    builder.PrependInt64Slot(3, bgmid3rd, 0)

def AddBgmid3rd(builder, bgmid3rd):
    BGMUIExcelAddBgmid3rd(builder, bgmid3rd)

def BGMUIExcelAddEventContentId(builder, eventContentId):
    builder.PrependInt64Slot(4, eventContentId, 0)

def AddEventContentId(builder, eventContentId):
    BGMUIExcelAddEventContentId(builder, eventContentId)

def BGMUIExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return BGMUIExcelEnd(builder)
