# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class ExternalBTNodeType(object):
    Sequence = 0
    Selector = 1
    Instant = 2
    SubNode = 3
    ExecuteAll = 4
