# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class FieldWorldMapButtonType(object):
    DefaultMode = 0
    Normal = 1
    Combat = 2
    Combat_VeryHard = 3
    UnderCover = 4
