# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class MeetupConditionType(object):
    None_ = 0
    EventContentStageClear = 1
    ScenarioClear = 2
