# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class MessagePopupLayout(object):
    TextOnly = 0
    ImageBig = 1
    ImageSmall = 2
    UnlockCondition = 3
