# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class ScenarioZoomAnchors(object):
    Center = 0
    LeftTop = 1
    LeftBottom = 2
    RightTop = 3
    RightBottom = 4
