# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class StarGoalType(object):
    None_ = 0
    AllAlive = 1
    Clear = 2
    GetBoxes = 3
    ClearTimeInSec = 4
    AllyBaseDamage = 5
