# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class AccountState(object):
    WaitingSignIn = 0
    Normal = 1
    Dormant = 2
    Comeback = 3
    Newbie = 4
