# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class CurrencyOverChargeType(object):
    CanNotCharge = 0
    FitToLimit = 1
    ChargeOverLimit = 2
