# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class DreamMakerEndingRewardType(object):
    None_ = 0
    FirstEndingReward = 1
    LoopEndingReward = 2
