# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class DreamMakerParamOperationType(object):
    None_ = 0
    GrowUpHigh = 1
    GrowUp = 2
    GrowDownHigh = 3
    GrowDown = 4
