# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class FieldTutorialType(object):
    None_ = 0
    MasteryHUD = 1
    QuestHUD = 2
    WorldMapHUD = 3
