# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldSeasonExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldSeasonExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldSeasonExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldSeasonExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldSeasonExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def EntryDateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def InstantEntryDateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def StartDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def EndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def LobbyBgmchangeStageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def FieldPrefabControlId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def FieldGetKeywordCallDialogEnum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def MasteryImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def FieldLobbyTitleImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def KeywordLogoImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FieldSeasonExcelStart(builder):
    builder.StartObject(12)

def Start(builder):
    FieldSeasonExcelStart(builder)

def FieldSeasonExcelAddUniqueId(builder, uniqueId):
    builder.PrependInt64Slot(0, uniqueId, 0)

def AddUniqueId(builder, uniqueId):
    FieldSeasonExcelAddUniqueId(builder, uniqueId)

def FieldSeasonExcelAddEventContentId(builder, eventContentId):
    builder.PrependInt64Slot(1, eventContentId, 0)

def AddEventContentId(builder, eventContentId):
    FieldSeasonExcelAddEventContentId(builder, eventContentId)

def FieldSeasonExcelAddEntryDateId(builder, entryDateId):
    builder.PrependInt64Slot(2, entryDateId, 0)

def AddEntryDateId(builder, entryDateId):
    FieldSeasonExcelAddEntryDateId(builder, entryDateId)

def FieldSeasonExcelAddInstantEntryDateId(builder, instantEntryDateId):
    builder.PrependInt64Slot(3, instantEntryDateId, 0)

def AddInstantEntryDateId(builder, instantEntryDateId):
    FieldSeasonExcelAddInstantEntryDateId(builder, instantEntryDateId)

def FieldSeasonExcelAddStartDate(builder, startDate):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(startDate), 0)

def AddStartDate(builder, startDate):
    FieldSeasonExcelAddStartDate(builder, startDate)

def FieldSeasonExcelAddEndDate(builder, endDate):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(endDate), 0)

def AddEndDate(builder, endDate):
    FieldSeasonExcelAddEndDate(builder, endDate)

def FieldSeasonExcelAddLobbyBgmchangeStageId(builder, lobbyBgmchangeStageId):
    builder.PrependInt64Slot(6, lobbyBgmchangeStageId, 0)

def AddLobbyBgmchangeStageId(builder, lobbyBgmchangeStageId):
    FieldSeasonExcelAddLobbyBgmchangeStageId(builder, lobbyBgmchangeStageId)

def FieldSeasonExcelAddFieldPrefabControlId(builder, fieldPrefabControlId):
    builder.PrependInt64Slot(7, fieldPrefabControlId, 0)

def AddFieldPrefabControlId(builder, fieldPrefabControlId):
    FieldSeasonExcelAddFieldPrefabControlId(builder, fieldPrefabControlId)

def FieldSeasonExcelAddFieldGetKeywordCallDialogEnum(builder, fieldGetKeywordCallDialogEnum):
    builder.PrependInt32Slot(8, fieldGetKeywordCallDialogEnum, 0)

def AddFieldGetKeywordCallDialogEnum(builder, fieldGetKeywordCallDialogEnum):
    FieldSeasonExcelAddFieldGetKeywordCallDialogEnum(builder, fieldGetKeywordCallDialogEnum)

def FieldSeasonExcelAddMasteryImagePath(builder, masteryImagePath):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(masteryImagePath), 0)

def AddMasteryImagePath(builder, masteryImagePath):
    FieldSeasonExcelAddMasteryImagePath(builder, masteryImagePath)

def FieldSeasonExcelAddFieldLobbyTitleImagePath(builder, fieldLobbyTitleImagePath):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(fieldLobbyTitleImagePath), 0)

def AddFieldLobbyTitleImagePath(builder, fieldLobbyTitleImagePath):
    FieldSeasonExcelAddFieldLobbyTitleImagePath(builder, fieldLobbyTitleImagePath)

def FieldSeasonExcelAddKeywordLogoImagePath(builder, keywordLogoImagePath):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(keywordLogoImagePath), 0)

def AddKeywordLogoImagePath(builder, keywordLogoImagePath):
    FieldSeasonExcelAddKeywordLogoImagePath(builder, keywordLogoImagePath)

def FieldSeasonExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldSeasonExcelEnd(builder)
