# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class FurnitureLocation(object):
    None_ = 0
    Inventory = 1
    Floor = 2
    WallLeft = 3
    WallRight = 4
