# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class PotentialStatBonusRateType(object):
    None_ = 0
    MaxHP = 1
    AttackPower = 2
    HealPower = 3
