# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class ScenarioModeReplayTypes(object):
    None_ = 0
    Event = 1
    Favor = 2
    Work = 3
    EventMeetup = 4
