# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class ScenarioBGType(object):
    None_ = 0
    Image = 1
    BlurRT = 2
    Spine = 3
    Hide = 4
