# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class StickerGetConditionType(object):
    None_ = 0
    StickerCheckPass = 1
    GetStickerCondition = 2
