# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Global

class StickerCheckPassType(object):
    None_ = 0
    ClearScenarioModeId = 1
    ClearCampaignStageId = 2
