mnemonics:
  0: return
  2: next
  3: Mif
  4: Mif
  5: loop
  6: goto
  7: wait
  8: waitnoslow
  17: m_push
  18: m_pop
  60: debugprint_word
  61: debugprint_int
  62: debugprint_float
  63: debugprint_float4
  64: debugprint_float3
  65: errorprint_word
  66: errorprint_int
  67: errorprint_float
  68: errorprint_float4
  69: errorprint_float3
  70: debugprint_lon
  80: strcpy
  81: strcat
  82: strcat_int
  100: sin
  101: cos
  103: atan2
  110: rand
  111: getrand_in
  112: getrand_float
  113: addrand_int
  114: addrand_float
  115: getdistance2d
  116: getdistance3d
  117: get2postorot
  118: posrottopos
  200: getmyid
  201: create
  202: free
  203: groupfree
  204: changeorder
  205: getgroupthread
  206: getorder
  210: setregisterint
  211: setregisterfloat
  212: getregisterint
  213: getregisterfloat
  214: setregisterlong
  215: getregisterlong
  230: js_free
  231: js_freejoint
  238: js_setthreadmode
  239: js_setthreadmodethreadgroup
  240: js_setvalue
  241: js_getvalue
  242: js_copyvalue
  243: js_changeanim
  244: js_changeanimspeed
  245: js_changedrawmode
  246: js_changeconvertermode
  247: js_setparent
  248: js_getglobalpos
  249: js_setthreadmodegroup
  250: jsa_simplepolygon2d
  253: jsa_mgp2
  254: jsa_simplepolygon3d
  255: jsa_afterimage
  257: jsa_simplepolygonbg
  260: jsa_moveline
  261: jsa_moveab
  262: jsa_moveinfinite
  263: jsa_lookrot
  264: jsa_anglemode
  265: jsa_movejump
  266: jsa_poslookrot
  267: jsa_movedirection
  268: jsa_movewait
  269: jsa_movewaitall
  280: js_getglobalrot
  281: js_getglobalscale
  282: js_getglobalcolor
  285: cw_play
  286: jsa_cwd
  287: js_setnoslowflag
  288: js_cw_runwait
  289: js_cw_isrun
  290: js_cw_setobjectflag
  291: js_cw_setcontrolflag
  292: js_cw_getcontrolflag
  293: js_cw_searchobjectthread
  294: js_cw_setobjectflagthread
  295: js_setruntype
  296: js_freeparent
  297: js_cw_getobjectflagthread
  298: js_cw_setglobalflag
  299: js_cw_getglobalflag
  300: js_getsoundinstallno
  301: js_playse
  302: js_playbgm
  303: js_playvoice
  305: js_setsoundposition
  310: js_memplayse
  311: js_fadevolume
  312: js_fadevolumeautofree
  313: js_soundhandleisplaying
  320: js_cw_setnoslowflag
  329: js_setjshtum_mode
